### ISSUE TITLE
Failure of the connection between Ros and UR caps

### ISSUE THREAD

**Issue by mymanon2000** [UniversalRobots/Universal_Robots_ROS_as_a_Service_URCap#46] opened 2022-10-18 09:16 UTC
Hello,

I have a problem when I want to add a publication to a topic directly on the UR. I followed the whole tutorial to the letter, but after launching the `roslaunch rosbridge_server rosbridge_tcp.launch` ,when I try to press on the UR interface the "Publish topic" button or any other one related to the UR caps, an error appears :

`[ERROR] [1666083196.581254]: [Client 0] call_service TypeError: send_message() takes from 1 to 2 positional arguments but 3 were given
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/pcmanon/ur_ros/src/rosbridge_suite-ros1/rosbridge_library/src/rosbridge_library/internal/services.py", line 75, in run
    self.success(call_service(self.service, self.args))
  File "/home/pcmanon/ur_ros/src/rosbridge_suite-ros1/rosbridge_library/src/rosbridge_library/capabilities/call_service.py", line 102, in _success
    self.protocol.send(outgoing_message)
  File "/home/pcmanon/ur_ros/src/rosbridge_suite-ros1/rosbridge_library/src/rosbridge_library/protocol.py", line 277, in send
    self.outgoing(serialized, compression)
TypeError: send_message() takes from 1 to 2 positional arguments but 3 were given
`
I work on an UR10e robot whit ros 1

**Comment by fmauch** [comment] 2022-11-16 20:58
I haven't been using this for a while now... I'll go ahead and test this.

**Comment by fmauch** [comment] 2022-11-16 21:05
I cannot reproduce this using ROS noetic and rosbridge_suite built from source (Since you seem to have done that) from version https://github.com/RobotWebTools/rosbridge_suite/commit/b0d0d711931d8ab7a5f079f948ced8875b4dc5d9.

**Comment by fmauch** [comment] 2024-06-12 08:16
I'm going to close this as there were no updates and we couldn't reproduce the error.

**Closed as completed by fmauch** 2024-06-12 08:16 UTC
Labels: question
